# generated by fastapi-codegen:
#   filename:  openapi-2.json
#   timestamp: 2021-05-26T13:18:58+00:00

from __future__ import annotations

from datetime import datetime
from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field
from enum import Enum

# TODO: Some error handling for models

class Schedule(BaseModel):
    id: Optional[int] = None
    assignee_id: int = Field(..., example=1312332)
    beginDate: datetime = Field(
        ...,
        example="2020-11-17T12:08:56.235-0100",
        description="Date format according to ISO_8601 for example: yyyy-MM-dd'T'HH:mm:ss.SSSZ",
    )
    endDate: datetime = Field(
        ...,
        example="2020-11-17T12:08:56.235-0100",
        description="Date format according to ISO_8601 for example: yyyy-MM-dd'T'HH:mm:ss.SSSZ",
    )

    class Config:
        orm_mode = True

class Breed(Enum):
    wikunia = 'wikunia'
    alpaka  = 'alpaka'
    guanako = 'guanako'
    lama    = 'lama'

class Llama(BaseModel):
    id: Optional[int] = None
    name: str = Field(..., example='Sniezka')
    age: int = Field(..., example=10)
    breed: Breed = Field(..., example="wikunia")
    color: str = Field(..., example='brown')
    coat: str = Field(..., example='podrozny')

    class Config:
        orm_mode = True


class CreateRequest(BaseModel):
    llama: Llama

class UpdateRequest(BaseModel):
    llama: Llama

class LlamaListResponse(BaseModel):
    llamaList: List[Llama]

class AddScheduleRequest(BaseModel):
    schedule: Schedule

class ScheduleListResponse(BaseModel):
    llamaList: Optional[List[Schedule]] = None

class Exception(BaseModel):
    code: Optional[int] = None
    detail: Optional[str] = None
